### ISSUE TITLE
Configuración de Issues.

### ISSUE THREAD

**Issue by ramamarquez2** [mgonzalesips/TrabajoSube#3]
Hola, noté que en mi repo forkeado y en el de algunos compañeros no están habilitados los Issues, creo que eso se configura desde tu repositorio, al menos eso leí en Internet. En el caso de que no sea así te pido una mano para solucionarlo, o será en clases. Gracias.

**Comment by mgonzalesips** [comment]
Si no tienen los issues activados, **en su repositorio**  van a settings -> general -> features y los activan.
